#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

#This is specific to you module, so you need to change it accordingly.
#agent.dump_env()
rdb = agent.redis_connect(use_replica=True)
ALLOWED_HOSTS = data.get('host')
 
agentzero = { 
"ALLOWED_HOSTS": ALLOWED_HOSTS,
}

agent.write_envfile("agentzero.env", agentzero) 

# just before starting systemd unit
agent.dump_env()
